[package]
name = "uti-derive"
version = "0.1.0"
authors = ["Jakob Meier <inbox@jakobmeier.ch>"]
edition = "2018"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
blake3 = "0.3.7"
uti = { path = "../uti" }

[lib]
proc-macro = true
