[package]
authors = ["Jakob Meier <inbox@jakobmeier.ch>"]
edition = "2018"
name = "uti"
version = "0.1.0"

[dependencies]
serde = {version = "1.0", features = ["derive"], optional = true}

[dev-dependencies]
uti-derive = {path = "../uti-derive"}

[features]
default = ["integer128"]
integer128 = []
